### ISSUE TITLE
Add missing ACF fields for post structured data

### ISSUE THREAD

**Issue by cjg89** [UCF/Coronavirus-Child-Theme#35]
**Describe the bug**

See title

**Steps to Reproduce**

View ACF config in repo; they're missing

**Expected Behavior**

They should be committed to the theme.

**Possible Fix**

Commit them.

**Your environment:**

 - Browser & Version [e.g. chrome 68, safari]
 - WordPress Version: [e.g. 4.9.8]
 - Theme Version: [e.g. 1.5.2]

**Additional context**

**Comment by jmbarne3** [comment]
They're there: https://github.com/UCF/Coronavirus-Child-Theme/blob/master/dev/acf-export.json#L781-L867
